services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8080:8080"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
